---
title: Systematic Literature Review <br>A Network Analysis
subtitle: NLP Workshop
format: 
  clean-revealjs
author:
  - name: Olivier Caron
    orcid: 0000-0000-0000-0000
    email: olivier.caron@dauphine.psl.eu
    affiliations:
      name: "Paris Dauphine - PSL"
      city: Paris
      state: France
  - name: Christophe Benavent
    orcid: 0000-0002-7253-5747
    email: christophe.benavent@dauphine.psl.eu
    affiliations:
      name: "Paris Dauphine - PSL"
      city: Paris
      state: France
date: last-modified
---
```{r}

```


```{python}
#| label: data-loading
#| include: false
#| eval: true
import pandas as pd

list_articles = pd.read_csv("data/nlp_full_data_final_18-08-2023.csv", sep=';', decimal=',')
list_articles = list_articles[list_articles['marketing'] == 1] #only marketing articles
list_references = pd.read_csv("data/nlp_references_final_18-08-2023.csv", sep=';', decimal=',')

```

## Research context 

### Systematic literature review of marketing papers using NLP techniques.
### What are the factors driving the diffusion of NLP technologies in the field of marketing research?



## Data presentation



### Some extra things you can do with the clean theme

Special classes for emphasis

- `.alert` class for default emphasis, e.g. [important note]{.alert}.
- `.fg` class for custom colour, e.g. [important note]{.fg style="--col: #e64173"}.
- `.bg` class for custom background, e.g. [important note]{.bg style="--col: #e64173"}.

Cross-references

- `.button` class provides a Beamer-like button, e.g.
[[Summary]{.button}](#sec-summary)

## Want more?

### See our longer demo slides

We've deliberarely kept this template lean, to get you up and running as fast as
possible.

We provide a separate
[demo template](https://github.com/grantmcdermott/quarto-revealjs-clean-demo),
with more examples for integrating code, tables, figures, etc.

  - See the live demo slides
  [here](https://grantmcdermott.com/quarto-revealjs-clean-demo/template.html).

## Summary {#sec-summary}

### A minimal and elegant presentation theme

The Quarto reveal.js clean theme aims to be a minimal and elegant presention
theme.

Install the theme.

```{.bash}
quarto install extension grantmcdermott/quarto-revealjs-clean
#{background-iframe="colored-particles/index.html"}
```

Use this lean template.

```{.bash}
quarto use template grantmcdermott/quarto-revealjs-clean
```

Use the longer demo template.

```{.bash}
quarto use template grantmcdermott/quarto-revealjs-clean-demo
```
